// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview Generates quiz questions from user-uploaded data.
 *
 * - suggestQuizQuestion - A function that generates a quiz question from user uploaded data.
 * - SuggestQuizQuestionInput - The input type for the suggestQuizQuestion function.
 * - SuggestQuizQuestionOutput - The return type for the suggestQuizQuestion function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestQuizQuestionInputSchema = z.object({
  data: z
    .string()
    .describe("User-uploaded data from which to generate quiz questions."),
});
export type SuggestQuizQuestionInput = z.infer<typeof SuggestQuizQuestionInputSchema>;

const SuggestQuizQuestionOutputSchema = z.object({
  question: z.string().describe("The generated quiz question."),
  answer: z.string().describe("The answer to the generated quiz question."),
});
export type SuggestQuizQuestionOutput = z.infer<typeof SuggestQuizQuestionOutputSchema>;

export async function suggestQuizQuestion(input: SuggestQuizQuestionInput): Promise<SuggestQuizQuestionOutput> {
  return suggestQuizQuestionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestQuizQuestionPrompt',
  input: {schema: SuggestQuizQuestionInputSchema},
  output: {schema: SuggestQuizQuestionOutputSchema},
  prompt: `You are an expert quiz question generator.

  You will use the user-uploaded data to generate a quiz question and its corresponding answer.

  Data: {{{data}}}
  `,
});

const suggestQuizQuestionFlow = ai.defineFlow(
  {
    name: 'suggestQuizQuestionFlow',
    inputSchema: SuggestQuizQuestionInputSchema,
    outputSchema: SuggestQuizQuestionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
